# Generated by Django 3.1 on 2021-05-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(help_text='The IP address the login was from', max_length=255, verbose_name='IP Address')),
                ('time', models.DateTimeField(help_text='The time and date of failed login', verbose_name='DateTime of failed login')),
            ],
            options={
                'verbose_name_plural': ' Failed logins',
            },
        ),
    ]
