# Generated by Django 3.2.12 on 2022-02-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerprint',
            options={'managed': False, 'permissions': [('upload_fingerprint', 'Can upload fingerprints'), ('view_nonsync_fingerprint', 'Can view non-shared fingerprints')]},
        ),
    ]
