# Generated by Django 3.2.12 on 2022-02-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0002_alter_fingerprint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerprint',
            options={'managed': False, 'permissions': [('upload_fingerprint', 'Can upload fingerprints'), ('view_nonsync_fingerprint', 'Can view non-shared fingerprints'), ('edit_comment_fingerprint', 'Can edit comments of fingerprints'), ('edit_sync_fingerprint', 'Can change shareability of fingerprints')]},
        ),
    ]
