# Generated by Django 3.2.14 on 2022-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0002_misp_sharing_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misp',
            name='sharing_group',
            field=models.CharField(blank=True, default='', help_text='Sharing Group to Dsitribute to, leave empty for default (Community)', max_length=255, verbose_name='Sharing Group'),
        ),
    ]
