# Generated by Django 3.1 on 2021-05-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0003_auto_20210525_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedlogin',
            old_name='time',
            new_name='logindatetime',
        ),
    ]
