# Generated by Django 3.2.12 on 2022-03-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_multitokenauth', '0003_pk_migration'),
        ('ddosdb', '0003_alter_fingerprint_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDoSToken',
            fields=[
                ('multitoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_rest_multitokenauth.multitoken')),
                ('description', models.CharField(default='', max_length=256, verbose_name='Description')),
            ],
            bases=('django_rest_multitokenauth.multitoken',),
        ),
    ]
