# Generated by Django 3.2.14 on 2023-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0004_auto_20220729_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misp',
            name='publish',
            field=models.BooleanField(default=False, help_text='Automatically publish'),
        ),
    ]
