# Generated by Django 3.2.12 on 2022-03-05 22:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ddosdb', '0004_ddostoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddostoken',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
