# Generated by Django 2.0.5 on 2018-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0004_accessrequest_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('view_blame', 'Can see blame information'),),
            },
        ),
    ]
