# Generated by Django 3.2.4 on 2021-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0005_auto_20210727_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteddosdb',
            name='active',
            field=models.BooleanField(default=True, help_text='Check this to sync with this DDoS-DB'),
        ),
        migrations.AlterField(
            model_name='remoteddosdb',
            name='pull',
            field=models.BooleanField(default=True, help_text='Sync from this DDoS-DB'),
        ),
        migrations.AlterField(
            model_name='remoteddosdb',
            name='push',
            field=models.BooleanField(default=False, help_text='Sync towards this DDoS-DB'),
        ),
    ]
