# Generated by Django 3.2.12 on 2022-03-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0005_auto_20220305_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddostoken',
            options={'permissions': [('add_token', 'Can add token'), ('view_token', 'Can view Token'), ('edit_token', 'Can change Token'), ('delete_token', 'Can delete Token')], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
