# Generated by Django 2.0.5 on 2018-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0006_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blame',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='blame',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
