# Generated by Django 3.2.12 on 2022-02-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0007_misp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misp',
            name='pull',
            field=models.BooleanField(default=False, help_text='Sync from this MISP'),
        ),
        migrations.AlterField(
            model_name='misp',
            name='push',
            field=models.BooleanField(default=True, help_text='Sync towards this MISP'),
        ),
    ]
