# Generated by Django 3.1 on 2020-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0009_auto_20180820_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Remote DDoS-DB')),
                ('api_url', models.CharField(max_length=256, verbose_name='Remote DDoS-DB URL')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
