# Generated by Django 3.1 on 2020-11-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0010_remotedb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemoteDB',
            new_name='RemoteDdosDb',
        ),
    ]
