# Generated by Django 3.1 on 2020-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0011_auto_20201120_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteddosdb',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
