# Generated by Django 3.1 on 2020-11-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0013_auto_20201120_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteddosdb',
            name='api_url',
            field=models.URLField(help_text='The full URL for the remote sync API', verbose_name='Remote DDoS-DB URL'),
        ),
        migrations.AlterField(
            model_name='remoteddosdb',
            name='name',
            field=models.CharField(help_text='A friendly name for the remote repository', max_length=32, verbose_name='Remote DDoS-DB'),
        ),
    ]
