# Generated by Django 3.1 on 2020-11-20 20:18

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0014_auto_20201120_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteddosdb',
            name='active',
            field=models.BooleanField(default=False, help_text='Activate to sync local fingerprints with this DDoS-DB'),
        ),
        migrations.AlterField(
            model_name='remoteddosdb',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remoteddosdb',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Remote Identity'),
        ),
    ]
