# Generated by Django 3.1 on 2020-11-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddosdb', '0015_auto_20201120_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteddosdb',
            old_name='api_url',
            new_name='url',
        ),
    ]
